version: '3.7'
services:
    simulator:
        build:
          context: .
          dockerfile: Dockerfile_base
        container_name: c3
        logging:
          options:
            max-size: "10m"
            max-file: "3"
        privileged: true
        environment:
          SDL_VIDEODRIVER: x11
          DISPLAY: ${DISPLAY}
          AUDIODEV: null
          AUDIODRIVER: alsa
          ALSA_CONFIG_PATH: /dev/null

          # SDL_VIDEODRIVER: x11
          # DISPLAY: $DISPLAY
          # AUDIODEV: null
          # AUDIODRIVER: alsa
          # ALSA_CONFIG_PATH: /dev/null
        ports:
            - "2000:2000"
            - "2001:2001"
            - "2002:2002"
        network_mode: "host"
        deploy:
          resources:
            reservations:
              devices:
                - driver: nvidia
                  count: 1
                  capabilities: ["gpu"]

        command: /opt/carla/CarlaUE4.sh  -quality-level=Low
        volumes:
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            - /etc/localtime:/etc/localtime
            - /etc/timezone:/etc/timezone
        restart: always

